base_url = "https://www.archaeoramblings.com"
title = "Archaeoramblings"
description = "Just random stuff from a random archaeologist"
default_language = "en"
author = "Andrea Titolo"
output_dir = "public"
compile_sass = false
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
build_search_index = false
minify_html = false
taxonomies = [
    { name = "tags", feed = true, paginate_by = 25 },
]
[slugify]
paths_keep_dates = true
[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["highlight_themes/catppuccin"]
highlight_theme = "css"
highlight_themes_css = [
  { theme = "catppuccin_latte", filename = "css/syntax-theme-dark.css" },
  { theme = "catppuccin_frappe", filename = "css/syntax-theme-light.css" },
]
[extra]
email = "298mtxjd@anonaddy.me"
avatar = "img/avatar.webp"
posts_to_show = 3
images_default_size = 720
images_sizes = [300, 600]
header_items = [
    { url = "/about/", name = "About" },
    { url = "/blog/", name = "Blog" },
    { url = "/bookmarks/", name = "Bookmarks" },
    { url = "/contact/", name = "Contact" },
    { url = "/more/", name = "More.." }
]
footer_items = [
    { url = "/now/", name = "Now" },
    { url = "/uses/", name = "Uses" },
    { url = "/links/", name = "Blogroll" },
    { url = "/metrics/", name = "Colophon" },
    { url = "/credits/", name = "Credits" },
    { url = "/tags/", name = "Tags" },
    { url = "/rss", name = "RSS" }
]
webrings = [
    { url = "https://fediring.net/", name = "Fediring", prev = "previous?host=", next = "next?host=", random = "true",  slug = "archaeoramblings.com", random_slug = "random", use_slug = "true"},
    { url = "https://webring.archaeo.social/", name = "Archaeoring", prev = "previous?host=", next = "next?host=", random = "true", slug = "archaeoramblings.com", random_slug = "random", use_slug = "true"},
    { url = "https://webring.dinhe.net/", name = "Retronaut", prev = "prev/", next = "next/", random = "false", slug = "https://www.archaeoramblings.com/", use_slug = "true"},
    { url = "https://itawebring.altervista.org/", name = "Itawebring", prev = "anello?d=prev&url=", next = "anello?d=next&url=", random = "true", slug = "https://www.archaeoramblings.com/", use_slug = "true", random_slug = "anello?d=rand"},
    { url = "https://geekring.net/", name = "Geekring", prev = "site/371/previous", next = "site/371/next", random = "true", slug = "https://www.archaeoramblings.com/", use_slug = "false", random_slug = "site/371/random"},
]
[extra.favicon]
favicon_ico = "/img/favicons/favicon.ico"
favicon_svg = "/img/favicons/icon.svg"
favicon_16x16 = "/img/favicons/android-chrome-192x192.png"
favicon_32x32 = "/img/favicons/android-chrome-512x512.png"
apple_touch_icon = "/img/favicons/apple-touch-icon.png"
safari_pinned_tab = "/img/favicons/safari-pinned-tab.svg"
webmanifest = "/img/favicons/site.webmanifest"
