[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.18.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = '''
      max-age=31536000;
      includeSubDomains;
      preload
    '''
    Content-Security-Policy = '''
      default-src 'self' https://*.poetic-blancmange-a64617;
      style-src 'self' https://*.poetic-blancmange-a64617 'unsafe-inline' data:;
      img-src 'self' https://*.poetic-blancmange-a64617 'unsafe-inline' data:;
      script-src 'self' https://*.poetic-blancmange-a64617 'unsafe-inline' 'unsafe-eval' cdn.jsdelivr.net cdnjs.cloudflare.com cdn.mathjax.org;
      frame-src 'self' https://*.poetic-blancmange-a64617;
	    connect-src 'self' https://*.poetic-blancmange-a64617;
	    base-uri 'self' https://*.poetic-blancmange-a64617;
	    form-action 'self' https://*.poetic-blancmange-a64617;
      font-src 'self' data:
    '''
    Permissions-Policy = '''
      accelerometer=(),
      ambient-light-sensor=(),
      autoplay=(),
      camera=(),
      encrypted-media=(),
      fullscreen=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      speaker=(),
      usb=(),
      vibrate=(),
      vr=()
    '''